<?php

namespace ContainerIQxF1dW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabase_ConnectionService extends Instana_RobotShop_Ratings_KernelDevDebugContainer
{
    /**
     * Gets the private 'database.connection' shared service.
     *
     * @return \PDO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Database.php';

        $a = new \Instana\RobotShop\Ratings\Database('mysql:host=mysql;dbname=ratings;charset=utf8mb4', 'ratings', 'iloveit');
        $a->setLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        return $container->privates['database.connection'] = $a->getConnection();
    }
}
