<?php

namespace ContainerIQxF1dW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthControllerService extends Instana_RobotShop_Ratings_KernelDevDebugContainer
{
    /**
     * Gets the public 'Instana\RobotShop\Ratings\Controller\HealthController' shared autowired service.
     *
     * @return \Instana\RobotShop\Ratings\Controller\HealthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/HealthCheckService.php';

        $a = new \Instana\RobotShop\Ratings\Service\HealthCheckService(($container->privates['database.connection'] ?? $container->load('getDatabase_ConnectionService')));

        $b = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $a->setLogger($b);

        $container->services['Instana\\RobotShop\\Ratings\\Controller\\HealthController'] = $instance = new \Instana\RobotShop\Ratings\Controller\HealthController($a);

        $instance->setLogger($b);

        return $instance;
    }
}
