<?php

namespace ContainerIQxF1dW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_LoggerService extends Instana_RobotShop_Ratings_KernelDevDebugContainer
{
    /**
     * Gets the private 'monolog.logger' shared service.
     *
     * @return \Symfony\Bridge\Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['monolog.logger'] = $instance = new \Symfony\Bridge\Monolog\Logger('app');

        $instance->pushProcessor(($container->privates['Instana\\RobotShop\\Ratings\\Integration\\InstanaHeadersLoggingProcessor'] ?? ($container->privates['Instana\\RobotShop\\Ratings\\Integration\\InstanaHeadersLoggingProcessor'] = new \Instana\RobotShop\Ratings\Integration\InstanaHeadersLoggingProcessor())));
        $instance->useMicrosecondTimestamps(true);
        $instance->pushHandler(($container->privates['monolog.handler.stdout'] ?? $container->getMonolog_Handler_StdoutService()));

        return $instance;
    }
}
