<?php

namespace ContainerIQxF1dW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingsApiControllerService extends Instana_RobotShop_Ratings_KernelDevDebugContainer
{
    /**
     * Gets the public 'Instana\RobotShop\Ratings\Controller\RatingsApiController' shared autowired service.
     *
     * @return \Instana\RobotShop\Ratings\Controller\RatingsApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/RatingsApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CatalogueService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RatingsService.php';

        $a = new \Instana\RobotShop\Ratings\Service\CatalogueService('http://catalogue:8080');

        $b = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $a->setLogger($b);
        $c = new \Instana\RobotShop\Ratings\Service\RatingsService(($container->privates['database.connection'] ?? $container->load('getDatabase_ConnectionService')));
        $c->setLogger($b);

        $container->services['Instana\\RobotShop\\Ratings\\Controller\\RatingsApiController'] = $instance = new \Instana\RobotShop\Ratings\Controller\RatingsApiController($a, $c);

        $instance->setLogger($b);

        return $instance;
    }
}
