<?php

namespace ContainerIQxF1dW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseEventService extends Instana_RobotShop_Ratings_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eTP2f4Q.Symfony\Component\HttpKernel\Event\ResponseEvent' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Event\ResponseEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eTP2f4Q": it references class "Symfony\\Component\\HttpKernel\\Event\\ResponseEvent" but no such service exists.');
    }
}
