<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQxF1dW\Instana_RobotShop_Ratings_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQxF1dW/Instana_RobotShop_Ratings_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQxF1dW.legacy');

    return;
}

if (!\class_exists(Instana_RobotShop_Ratings_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQxF1dW\Instana_RobotShop_Ratings_KernelDevDebugContainer::class, Instana_RobotShop_Ratings_KernelDevDebugContainer::class, false);
}

return new \ContainerIQxF1dW\Instana_RobotShop_Ratings_KernelDevDebugContainer([
    'container.build_hash' => 'IQxF1dW',
    'container.build_id' => '15fbaef5',
    'container.build_time' => 1644445787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQxF1dW');
