apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-catalogue
  labels:
    service: {{ .Release.Name }}-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-catalogue
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-catalogue
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: {{ .Release.Name }}
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-catalogue
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-catalogue:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.opentelemetry.exporter.otlp.endpoint }}
        {{- if ne .Values.opentelemetry.exporter.otlp.headers "" }}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: {{ .Values.opentelemetry.exporter.otlp.headers }}
        {{- end }}
        - name: OTEL_SERVICE_NAME
          value: {{ .Release.Name }}-catalogue
        - name: MONGO_URL
          value: 'mongodb://{{ .Release.Name }}-mongodb:27017/users'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      - name: {{ .Release.Name }}-catalogue-otelcol-sidecar
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-otel-collector:{{ .Values.image.version }}
        args:
        - --config=/conf/agent.yaml
        volumeMounts:
        - mountPath: /conf
          name: {{ .Release.Name }}-agent-config
      volumes:
      - configMap:
          items:
          - key: agent.yaml
            path: agent.yaml
          name: {{ .Release.Name }}-agent-config
        name: {{ .Release.Name }}-agent-config
      restartPolicy: Always
