apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  labels:
    service: {{ .Release.Name }}-front
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: {{ .Release.Name }}-front
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-front
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-front
{{end}}
