---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
    exporters:
      otlp:
        endpoint: "{{ .Release.Name }}-opentelemetrycollector.default.svc.cluster.local:4317"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-opentelemetrycollector
    spec:
      containers:
      - name: otelcol
        args:
        - --config=/conf/collector.yaml
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-otel-collector:{{ .Values.image.version }}
        volumeMounts:
        - mountPath: /conf
          name: {{ .Release.Name }}-collector-config
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: {{ .Release.Name }}-collector-config
        name: {{ .Release.Name }}-collector-config
