apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opentelemetrycollector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-opentelemetrycollector
  type: ClusterIP
